apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: api
    context: .
    docker:
      dockerfile: API.Dockerfile
deploy:
  kubectl:
    manifests:
    - ./ingress.yaml
    - ./API/*.yaml