apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: api
    context: .
    docker:
      dockerfile: API.Dockerfile
  - image: postgres
    context: .
    docker:
      dockerfile: Postgres.Dockerfile
deploy:
  kubectl:
    manifests:
    - ClusterVersionCRD.yaml
    - SiloEntryCRD.yaml
    - postgres.yaml
    - ingress.yaml
    - API/*.yaml